
// Edge types generated by frontend
// Used to determine whether data will be used to read (saved at index 0 in sourceConnecter)
// Or used to update a value (saved at index 1 in sourceConnector)

const sourceTypes = Object.freeze({
    FIND: 'find',
    UPDATE: 'update',
    INSERT: 'insert',
    INPUT: 'input',
});

export default sourceTypes;